### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [bruce/atom-csscomb#30]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.1.2`) of this package:

1. Use `activationCommands` instead of `activationEvents` in your package.json Commands should be grouped by selector as follows: ```json "activationCommands": { "atom-workspace": ["foo:bar", "foo:baz"], "atom-text-editor": ["foo:quux"] } ```
1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
1. Use Workspace::getActivePaneItem instead
1. Use `Project::getDirectories()[0]?.resolve()` instead
1. Use editor.lineTextForBufferRow(row).length instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by stramel** [comment]
@benogle @bruce  It seems a lot of the deprecation issues have been addressed in PRs but have not been merged.

1. Use `activationCommands` instead of `activationEvents` in package.json
  - Addressed by PR #28 
2. `atom.workspaceView` is no longer available.
  - Addressed by PR #20 
3. Use `Workspace::getActivePaneItem` instead of ____ ?
  - **Needs addressed.**
4. Use `Project::getDirectories()[0]?.resolve()` instead of _____?
  - **Needs addressed.**
5. Use `editor.lineTextForBufferRow(row).length` instead of _____?
  - **Needs addressed.**

Other deprecated commands not listed in original list:

6. Use `atom-workspace` tag instead of the `workspace` class
  - Addressed by PR #18. PR #21 should be closed in favor of #18.

Package Specific PRs that need addressed:

7. Updates the project dependencies as well as cleans up the coding style of the project
  - Addressed by PR #16. PR #11 should be closed in favor of #16.
8. Update to allow SASS files to be combed
  - Addressed by PR #13 

@bruce I am tempted to fork this project and consolidate all the changes and/or push out a separate project that is updated and maintained.

**Comment by stramel** [comment]
Completed and released v0.3.0

Thank you for your help @benogle, @bruce, and all that submitted PRs.
